### ISSUE TITLE
error while evaluating conditional: ansible_os_family=="Debian"

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#255]
I started a new install and this is the error i received
```bash
root@ansible:~/DevOps/Ansible# ansible-playbook -i inventories/inventory.UNILAG idp-ldap.yml  -vv

PLAY [Configure the LDAP machine] ********************************************* 
ldapnew.unilag.edu.ng: importing group_vars/passwords-UNILAG.yml

TASK: [fmarco76.firewall | Retrieve iptables rules] *************************** 
<ldapnew.unilag.edu.ng> 
ok: [ldapnew.unilag.edu.ng] => {"changed": false, "cmd": ["iptables", "-t", "filter", "-L", "-n"], "delta": "0:00:00.003004", "end": "2015-07-24 14:26:48.343511", "rc": 0, "start": "2015-07-24 14:26:48.340507", "stderr": "", "stdout": "Chain INPUT (policy ACCEPT)\ntarget     prot opt source               destination         \nACCEPT     tcp  --  196.45.48.194        0.0.0.0/0           state NEW tcp dpt:636 \nACCEPT     tcp  --  196.45.48.194        0.0.0.0/0           state NEW tcp dpt:389 \n\nChain FORWARD (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination         ", "stdout_lines": ["Chain INPUT (policy ACCEPT)", "target     prot opt source               destination         ", "ACCEPT     tcp  --  196.45.48.194        0.0.0.0/0           state NEW tcp dpt:636 ", "ACCEPT     tcp  --  196.45.48.194        0.0.0.0/0           state NEW tcp dpt:389 ", "", "Chain FORWARD (policy ACCEPT)", "target     prot opt source               destination         ", "", "Chain OUTPUT (policy ACCEPT)", "target     prot opt source               destination         "], "warnings": []}

TASK: [fmarco76.firewall | Count iptables rules] ****************************** 
ok: [ldapnew.unilag.edu.ng] => {"changed": false, "rc": 0, "stderr": "", "stdout": "2", "stdout_lines": ["2"]}

TASK: [fmarco76.firewall | Apply rules for the local network] ***************** 
skipping: [ldapnew.unilag.edu.ng] => (item=389)
skipping: [ldapnew.unilag.edu.ng] => (item=636)

TASK: [fmarco76.firewall | Apply rules for the defined network] *************** 
skipping: [ldapnew.unilag.edu.ng] => (item=389)
skipping: [ldapnew.unilag.edu.ng] => (item=636)

TASK: [fmarco76.firewall | Apply nat rules] *********************************** 
skipping: [ldapnew.unilag.edu.ng] => (item=389)
skipping: [ldapnew.unilag.edu.ng] => (item=636)

TASK: [fmarco76.firewall | Save iptable rules] ******************************** 
fatal: [ldapnew.unilag.edu.ng] => error while evaluating conditional: ansible_os_family=="Debian" and ( applied_rules_local.changed or applied_rules_defined.changed or applied_rules_nat.changed )

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/idp-ldap.retry

ldapnew.unilag.edu.ng      : ok=5    changed=0    unreachable=1    failed=0   
```

**Comment by brucellino** [comment]
I can't see the inventory that you're using in the repo - I suspect that there's a problem with the groups. The network tasks are all being skipped, so some of the variables needed are not being set, which is why the logic is failing. Please commit your inventory file to the repo and check that it has groups for the machines based on operating system type.

e.g  : 
```
[CentOS-servers]
vm03.ct.infn.it
vm04.ct.infn.it

[Debian-servers]
#vm01.ct.infn.it
#vm02.ct.infn.it
```

**Comment by okoliec** [comment]
@brucellino:, below is my inventory file
root@ansible:~/DevOps/Ansible# less inventories/inventory.UNILAG
# UNILAG Inventory
[ldap-servers]
ldapnew.unilag.edu.ng

[shibboleth-idps]
idp.unilag.edu.ng

[CentOS-servers:children]
#ldap-servers
shibboleth-idps

[Debian-servers]
#ldapnew.unilag.edu.ng
[identity-UNILAG:children]
ldap-servers
#shibboleth-idps

**Comment by brucellino** [comment]
So, your shibboleth idp is a CentOS machine - but why is the ldap server not defined under either Debian or CentOS groups ?

**Comment by okoliec** [comment]
Yes it is.
I commented it out because  i thought my error my coming from there. This is what i have now but am still getting the same error.

# UNILAG Inventory
[ldap-servers]
ldapnew.unilag.edu.ng

[shibboleth-idps]
idp.unilag.edu.ng

[CentOS-servers:children]
ldap-servers
shibboleth-idps

[Debian-servers]
ldapnew.unilag.edu.ng
[identity-UNILAG:children]
ldap-servers
shibboleth-idps

**Comment by brucellino** [comment]
You have put your ldap server into both the CentOS and the Debian groups though - this is not possible. If it's a Debian machine, you should have 
```
[Debian-servers:children]
ldap-servers
```

Likewise if it's a CentOS machine, you should have

```
[CentOS-servers:children]
ldap-servers
```

**Comment by okoliec** [comment]
idp.unilag.edu.ng=Centos Machine
ldapnew.unilag.edu.ng=Debian Machine

# UNILAG Inventory
[ldap-servers]
ldapnew.unilag.edu.ng

[shibboleth-idps]
idp.unilag.edu.ng

[CentOS-servers:children]
shibboleth-idps

[Debian-servers]
ldapnew.unilag.edu.ng
[identity-UNILAG:children]
ldap-servers

But am still getting the same error

**Comment by brucellino** [comment]
Ok - one issue which should be fixed, but which is probbaly not causing your problem is this : 

```
[Debian-servers]
ldapnew.unilag.edu.ng
```

This should be : 

```
[Debian-servers:children]
ldap-servers
```
since it is a group (Debian servers) of a group (ldap-servers).

Now, the task is failing because some variables are not set - I see that it's picking up your passwords variable file, which is good, but not the OS-related one.

**Comment by okoliec** [comment]
Still getting the same error. See my inventory.UNILAG
# UNILAG Inventory
[ldap-servers]
ldapnew.unilag.edu.ng

[shibboleth-idps]
idp.unilag.edu.ng

[CentOS-servers:children]
shibboleth-idps

[Debian-servers:children]
ldap-servers

**Comment by brucellino** [comment]
I think this is due to a `gather_facts: no` in the playbook. this was incorrectly committed and should be removed.

**Comment by okoliec** [comment]
@brucellino: this seems to work now. But i still have another error with certificate. Can i proceed without the certificate
TASK: [shibboleth-idp | Debug subject] **************************************** 
ok: [idp.unilag.edu.ng] => {
    "{{ subject.stdout | regex_replace('^.*N(.*)$' ) }}": "{{ subject.stdout | regex_replace('^.*N(.*)$' ) }}"
}

TASK: [shibboleth-idp | debug CA certs] *************************************** 
ok: [idp.unilag.edu.ng] => {
    "cert_CA_certificates": "cert_CA_certificates"
}

TASK: [shibboleth-idp | Push the intermediate and root cert] ****************** 
fatal: [idp.unilag.edu.ng] => input file not found at /root/DevOps/Ansible/roles/shibboleth-idp/files/roles/certificates/files/commercial/{# cert_CA_certificates #} or /root/DevOps/Ansible/roles/certificates/files/commercial/{# cert_CA_certificates #}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/idp-ldap.retry

idp.unilag.edu.ng          : ok=24   changed=0    unreachable=1    failed=0   
ldapnew.unilag.edu.ng      : ok=24   changed=0    unreachable=0    failed=0

**Comment by brucellino** [comment]
Hi @okoliec - good to hear. To stick to to the contributor guidelines, I will close this issue. Can you please open a new one with the new error ? 
thanks!
